* Error (criu/vdso.c:*): vdso: Unexpected rt vDSO area bounds
* Error (criu/vdso.c:*): vdso: Failed to fill self vdso symtable
* File "check-application", line *, in testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in NOT_RUNNING)
